"""Initial schema: stocks, mutual_funds, prices, fundamentals, scores

Revision ID: 09908929e295
Revises: 
Create Date: 2026-04-06 02:11:53.906027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09908929e295'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_per_gram_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_gold_prices_date')
    )
    op.create_index(op.f('ix_gold_prices_date'), 'gold_prices', ['date'], unique=True)
    op.create_table('mutual_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_code', sa.String(length=20), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutual_funds_scheme_code'), 'mutual_funds', ['scheme_code'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tickers_total', sa.Integer(), nullable=True),
    sa.Column('tickers_success', sa.Integer(), nullable=True),
    sa.Column('tickers_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('flock_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('score_balanced', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_growth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_conservative', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pillar_profitability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pillar_growth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pillar_health', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pillar_valuation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pillar_quality', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id')
    )
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_profit_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('revenue_cagr_3yr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_growth_3yr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('peg_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('promoter_holding_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('promoter_pledge_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fii_dii_trend', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id')
    )
    op.create_table('mf_navs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['mutual_funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'date', name='uq_mf_navs_fund_date')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_stock_prices_stock_date')
    )
    op.create_index('ix_stock_prices_stock_date_desc', 'stock_prices', ['stock_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_prices_stock_date_desc', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_table('mf_navs')
    op.drop_table('fundamentals')
    op.drop_table('flock_scores')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_mutual_funds_scheme_code'), table_name='mutual_funds')
    op.drop_table('mutual_funds')
    op.drop_index(op.f('ix_gold_prices_date'), table_name='gold_prices')
    op.drop_table('gold_prices')
    # ### end Alembic commands ###
